[package]
name = "next_parser"
version = "0.1.0"
authors = ["shintaro.sakata <shintaro.sakata.tokyo@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "1"
